spring.application.name=java
server.port=${PORT:8080}

# Configuration for Supabase
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.drntgntjbsouttmabrpo
spring.datasource.password=EmYang@GK@2106
spring.datasource.driver-class-name=org.postgresql.Driver
# update Database khi Entity thay đổi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=false
